/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ff {

import org.apache.thrift.Set;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.protocol.*;


  public class chat_msg_t implements TBase   {
    private static const STRUCT_DESC:TStruct = new TStruct("chat_msg_t");
    private static const KEY_FIELD_DESC:TField = new TField("key", TType.LIST, 1);
    private static const VALUE_FIELD_DESC:TField = new TField("value", TType.STRING, 2);

    private var _key:Array;
    public static const KEY:int = 1;
    private var _value:String;
    public static const VALUE:int = 2;


    public static const metaDataMap:Dictionary = new Dictionary();
    {
      metaDataMap[KEY] = new FieldMetaData("key", TFieldRequirementType.DEFAULT, 
          new ListMetaData(TType.LIST, 
              new FieldValueMetaData(TType.I32)));
      metaDataMap[VALUE] = new FieldMetaData("value", TFieldRequirementType.DEFAULT, 
          new FieldValueMetaData(TType.STRING));
    }
    {
      FieldMetaData.addStructMetaDataMap(chat_msg_t, metaDataMap);
    }

    public function chat_msg_t() {
    }

    public function get key():Array {
      return this._key;
    }

    public function set key(key:Array):void {
      this._key = key;
    }

    public function unsetKey():void {
      this.key = null;
    }

    // Returns true if field key is set (has been assigned a value) and false otherwise
    public function isSetKey():Boolean {
      return this.key != null;
    }

    public function get value():String {
      return this._value;
    }

    public function set value(value:String):void {
      this._value = value;
    }

    public function unsetValue():void {
      this.value = null;
    }

    // Returns true if field value is set (has been assigned a value) and false otherwise
    public function isSetValue():Boolean {
      return this.value != null;
    }

    public function setFieldValue(fieldID:int, value:*):void {
      switch (fieldID) {
      case KEY:
        if (value == null) {
          unsetKey();
        } else {
          this.key = value;
        }
        break;

      case VALUE:
        if (value == null) {
          unsetValue();
        } else {
          this.value = value;
        }
        break;

      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function getFieldValue(fieldID:int):* {
      switch (fieldID) {
      case KEY:
        return this.key;
      case VALUE:
        return this.value;
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
    public function isSet(fieldID:int):Boolean {
      switch (fieldID) {
      case KEY:
        return isSetKey();
      case VALUE:
        return isSetValue();
      default:
        throw new ArgumentError("Field " + fieldID + " doesn't exist!");
      }
    }

    public function read(iprot:TProtocol):void {
      var field:TField;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case KEY:
            if (field.type == TType.LIST) {
              {
                var _list2:TList = iprot.readListBegin();
                this.key = new Array();
                for (var _i3:int = 0; _i3 < _list2.size; ++_i3)
                {
                  var _elem4:int;
                  _elem4 = iprot.readI32();
                  this.key.push(_elem4);
                }
                iprot.readListEnd();
              }
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case VALUE:
            if (field.type == TType.STRING) {
              this.value = iprot.readString();
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();


      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public function write(oprot:TProtocol):void {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (this.key != null) {
        oprot.writeFieldBegin(KEY_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.I32, this.key.length));
          for each (var elem5:* in this.key)          {
            oprot.writeI32(elem5);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (this.value != null) {
        oprot.writeFieldBegin(VALUE_FIELD_DESC);
        oprot.writeString(this.value);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public function toString():String {
      var ret:String = new String("chat_msg_t(");
      var first:Boolean = true;

      ret += "key:";
      if (this.key == null) {
        ret += "null";
      } else {
        ret += this.key;
      }
      first = false;
      if (!first) ret +=  ", ";
      ret += "value:";
      if (this.value == null) {
        ret += "null";
      } else {
        ret += this.value;
      }
      first = false;
      ret += ")";
      return ret;
    }

    public function validate():void {
      // check for required fields
      // check that fields of type enum have valid values
    }

  }

}
