#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

error_code_desc = {
  0 : "OK",
  1 : "系统错误",
  2 : "输入错误",
  3 : "系统忙",
  4 : "此账号已被占用",
  5 : "此账号无效",
  6 : "密码错误",
}
